image: ubuntu:latest

pages:
  stage: deploy
  script:
  # https://stackoverflow.com/a/58072486
  - apt-get update
  - apt-get install -y python3-pip
  - apt-get install -y language-pack-en
  - apt-get install -y language-pack-zh-hant
  - apt-get install -y language-pack-th
  - pip3 install -r requirements.txt
  - make download
  - make gitlab-pages
  artifacts:
    paths:
    - public/
  only:
  - master
